create table user, admin, category, subcategory, place, item, and request \nBUG! : error raised AttributeError: partially initialized module 'users.models' has no attribute 'User' (most likely due to a circular import)